"""
Generated by CHARMM-GUI (http://www.charmm-gui.org)

omm_restratins.py

This module contains restraint functions for OpenMM.

Correspondance: jul316@lehigh.edu or wonpil@lehigh.edu
Last update: March 29, 2017
"""

import mdtraj as md
import numpy as np
from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *


def restraints(system, crd, inputs, turns, state):

    # position restraints for protein
    posres = CustomExternalForce("fc_pos*periodicdistance(x,y,z,x0,y0,z0)^2")
    posres.addPerParticleParameter("fc_pos")
    posres.addPerParticleParameter("x0")
    posres.addPerParticleParameter("y0")
    posres.addPerParticleParameter("z0")

    atoms = crd.topology.atoms()

    restr_list = list()
    # restraint the alpha carbon
    if (
        inputs.rest_type == "CA"
        and turns == inputs.turn
        and state != "NVT"
        and state != "NPT"
    ):
        for x in atoms:
            if x.name == "CA":
                restr_list.append(x.index)
    else:
        # restraint all non-hydrogen atoms
        for x in atoms:
            if x.element != None:
                if x.residue.name not in (
                    "HOH",
                    "SOL",
                    "WAT",
                    "SWM4",
                    "SWM6",
                    "SWM",
                    "POT",
                ):
                    if x.element.symbol != "H":
                        # print(x.name,x.index,x.id,x.residue,x.element.symbol,x.element.name,x.element.mass)
                        restr_list.append(x.index)

    for i in restr_list:
        xpos = crd.positions[i].value_in_unit(angstroms)[0] / 10
        ypos = crd.positions[i].value_in_unit(angstroms)[1] / 10
        zpos = crd.positions[i].value_in_unit(angstroms)[2] / 10
        if inputs.turn != 0:
            posres.addParticle(
                i,
                [
                    1000 * (1 - (1 / inputs.turn) * turns) + inputs.fc_pos,
                    xpos,
                    ypos,
                    zpos,
                ],
            )
        else:
            posres.addParticle(i, [1000 + inputs.fc_pos, xpos, ypos, zpos])
    system.addForce(posres)

    return system


def restraint_ligand(system, crd, inputs):
    """This function is used to restrain the ligand into the pocket. When the ligand is in the pocket, there will be no force. 
    But if the ligand go out of the pocket, here will be a foce to pull it back. The pocket is defined as the space within 10A 
    of mass center of residues within 5A of crystal ligand."""
    traj = md.load(inputs.pdbfile)
    topology = traj.topology

    coordinates = []
    with open("crystal_ligand.pdb", "r") as f:
        for line in f.readlines():
            if line[:4] == "ATOM" or line[:6] == "HETATM":
                coordinates.append(
                    [
                        float(line[31:39]) / 10,
                        float(line[39:47]) / 10,
                        float(line[47:55]) / 10,
                    ]
                )
    ligand = np.array([list(map(float, item[0:3])) for item in coordinates])

    atoms = crd.topology.atoms()
    pocket_residue = []
    pocket_atom = []
    for x in atoms:
        if x.element != None:
            if x.residue.name not in (
                "HOH",
                "SOL",
                "WAT",
                "SWM4",
                "SWM6",
                "SWM",
                "POT",
                "LIG",
            ):
                if x.element.symbol != "H":
                    # print(x.name,x.index,x.id,x.residue,x.element.symbol,x.element.name,x.element.mass)
                    xpos = crd.positions[x.index].value_in_unit(angstroms)[0] / 10
                    ypos = crd.positions[x.index].value_in_unit(angstroms)[1] / 10
                    zpos = crd.positions[x.index].value_in_unit(angstroms)[2] / 10
                    pocket = np.array([[xpos, ypos, zpos]])
                    if (
                        np.min(
                            np.sqrt(
                                np.sum(
                                    ((pocket[:, np.newaxis][:] - ligand) ** 2), axis=2,
                                )
                            )
                        )
                        <= 0.5
                    ):
                        if x.residue.index not in pocket_residue:
                            pocket_residue.append(x.residue.index)

    atoms = crd.topology.atoms()
    for x in atoms:
        if x.element != None:
            if x.residue.name not in (
                "HOH",
                "SOL",
                "WAT",
                "SWM4",
                "SWM6",
                "SWM",
                "POT",
                "LIG",
            ):
                if x.name == "CA":
                    if x.residue.index in pocket_residue:
                        pocket_atom.append(x.index)

    ligand = topology.select("resname LIG")
    g2 = ligand.tolist()

    posres = CustomCentroidBondForce(
        2, "fc_pos*max(0,distance(g1,g2)-%s)^2" % (str(inputs.pocket / 10))
    )
    posres.setUsesPeriodicBoundaryConditions(True)
    posres.addPerBondParameter("fc_pos")
    posres.addGroup(pocket_atom)
    posres.addGroup(g2)
    bondGroups = [0, 1]
    posres.addBond(bondGroups, [inputs.fc_pos_lig])
    system.addForce(posres)
    return system
